project_name: mockserver
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - binary: mockserver
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -X main.builtBy=goreleaser
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format_overrides:
      - goos: windows
        format: zip
release:
  prerelease: auto
